version: "3"

services:
    # Контейнер с Node.js
    app:
        container_name: api_universal
        build:
            context: ./app
            target: dev
        tty: true
        working_dir: /opt/server
        volumes:
            - ./app:/opt/server
            - ./static:/opt/static
        env_file:
            - .env
        expose:
            - "3000"
        depends_on:
            - db

    # Контейнер с базой данных
    db:
        container_name: db
        image: postgres:12-alpine
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - ./postgres:/var/lib/postgresql/data
        expose:
            - "5432"
        restart: always

    # Контейнер с nginx
    nginx:
        container_name: proxy_nginx
        depends_on:
            - app
            - db
            - pgadmin
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - ./static:/var/www/static
        restart: always

    # Контейнер с pgadmin
    pgadmin:
        container_name: pgadmin
        depends_on:
            - db
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: serded59@ya.ru
            PGADMIN_DEFAULT_PASSWORD: qwerty13579
        expose:
            - "80"
        restart: always
